version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:latest
        volumes:
            - ./code:/code
        networks:
            - code-network
    mariadb:
        image: mariadb:latest
        volumes:
            - ./wpdb:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
